In [ ]:
import numpy as np
import math

## Mean and Std

In [ ]:
a = np.array([[1, 2],[3, 4]])
print(a)

In [ ]:
np.mean(a)

In [ ]:
np.mean(a, axis=1)

In [ ]:
mean = a.sum()/4

In [ ]:
mean

In [ ]:
a

In [ ]:
np.std(a)

In [ ]:
np.std(a, axis = 0)

$$S^2=\frac{(1-2.5)^2+(2-2.5)^2+(3-2.5)^2+(4-2.5)^2}{4}$$

In [ ]:
std = math.sqrt(((1-2.5)**2+(2-2.5)**2+(3-2.5)**2+(4-2.5)**2)/4)
std

In [ ]:
std = np.sqrt(((a - a.mean())**2/4).sum())
std

In [ ]:
np.std(a, ddof = 0)

$$ 2x_1 + 4x_2 + 2x_3 = 16 $$
$$ -2x_1 - 3x_2 + x_3 = -5 $$
$$ 2x_1 + 2x_2 - 3x_3 = -3 $$

$$\begin{bmatrix}
2 & 4 & 2\\
-2 & -3 & 1\\
2 & 2 & -3 
\end{bmatrix}\begin{bmatrix}
x_1\\
x_2\\
x_3\end{bmatrix} = \begin{bmatrix}
16\\
-5\\
-3\end{bmatrix} $$


In [1]:
import numpy.linalg as LA
import numpy as np

In [2]:
A = np.array([[2, 4, 2],[-2, -3, 1],[2, 2, -3]])
B = np.array([16, -5, -3])

A

array([[ 2,  4,  2],
       [-2, -3,  1],
       [ 2,  2, -3]])

In [3]:
sol = LA.solve(A, B)

sol

array([1., 2., 3.])

In [4]:
A @ sol

array([16., -5., -3.])

In [5]:
np.dot(A, sol)

array([16., -5., -3.])

$$\begin{bmatrix}
2 & 4 & 2\\
-2 & -3 & 1\\
2 & 2 & -3 
\end{bmatrix}\begin{bmatrix}
1\\
2\\
3\end{bmatrix}  $$


$$\rho = \frac{1}{4}\begin{bmatrix}
2 & 1 & 1\\
1 & 1 & 0\\
1 & 0 & 1 
\end{bmatrix}$$

$$\rho \vec{v} = \lambda \vec{v}$$

In [6]:
rho = (0.25)*np.array([[2, 1, 1],[1, 1, 0],[1, 0, 1]])

rho

array([[0.5 , 0.25, 0.25],
       [0.25, 0.25, 0.  ],
       [0.25, 0.  , 0.25]])

In [7]:
D, U = LA.eig(rho)

D

array([ 7.5000000e-01, -7.2858386e-17,  2.5000000e-01])

In [8]:
U

array([[-8.16496581e-01, -5.77350269e-01, -1.57009246e-16],
       [-4.08248290e-01,  5.77350269e-01, -7.07106781e-01],
       [-4.08248290e-01,  5.77350269e-01,  7.07106781e-01]])

In [13]:
rho @ U[:, 0]

array([-0.61237244, -0.30618622, -0.30618622])

In [14]:
D[0] * U[:, 0]

array([-0.61237244, -0.30618622, -0.30618622])

$$ \rho = UDU^{\text{T}}$$

In [18]:
U @ U.T

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [16]:
U @ np.diag(D) @ U.T

array([[ 5.00000000e-01,  2.50000000e-01,  2.50000000e-01],
       [ 2.50000000e-01,  2.50000000e-01, -4.16333634e-17],
       [ 2.50000000e-01, -6.93889390e-17,  2.50000000e-01]])

In [17]:
rho

array([[0.5 , 0.25, 0.25],
       [0.25, 0.25, 0.  ],
       [0.25, 0.  , 0.25]])